project_id = "amhpjsmubciahslghobw"

[functions.auto-assign-delivery-agents]
verify_jwt = false

[functions.check-unaccepted-orders]
verify_jwt = false

[functions.create-customer-app-subscription]
verify_jwt = false

[functions.export-stock-report]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.google-places]
verify_jwt = false

[functions.handle-subscription-delivery-action]
verify_jwt = false

[functions.notify-delivery-agents]
verify_jwt = false

[functions.process-daily-subscriptions]
verify_jwt = false

[functions.scan-missed-deliveries]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false

[functions.sendLiveOrderNotification]
verify_jwt = false

[functions.sync-subscription-dates]
verify_jwt = false

[functions.update-subscription-dates]
verify_jwt = false
